import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { PrimeReactProvider } from 'primereact/api';
import Tailwind from "primereact/passthrough/tailwind";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <PrimeReactProvider value={{ unstyled: true, pt: {} }}>
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
      </PrimeReactProvider>
  );
}
